### ISSUE TITLE
bug: headers already sent

### ISSUE THREAD

**Issue by RoundAboutWEB** [Crocoblock/jet-ai-search#1]
WP: 6.3.1
jet-engine: 3.2.4
jet-search: 3.1.1
problem: The plugin permanently causes the following warnings:

**PHP-Version: 7.4-latest FPM (7.4.33) (P+):**

```
PHP Warning:  Cannot modify header information - headers already sent in /html/wordpress/wp-content/plugins/jet-search/includes/ajax-handlers.php on line 223
PHP Warning:  session_id(): Cannot change session id when headers already sent in /html/wordpress/wp-content/plugins/jet-search/includes/ajax-handlers.php on line 185
PHP Warning:  session_start(): Cannot start session when headers already sent in /html/wordpress/wp-content/plugins/jet-search/includes/ajax-handlers.php on line 187
```

**PHP-Version: 8.0-latest FPM (8.0.29) (P+):**
```
PHP Warning:  Cannot modify header information - headers already sent in /html/wordpress/wp-content/plugins/jet-search/includes/ajax-handlers.php on line 223
PHP Warning:  session_id(): Session ID cannot be changed after headers have already been sent in /html/wordpress/wp-content/plugins/jet-search/includes/ajax-handlers.php on line 185
PHP Warning:  session_start(): Session cannot be started after headers have already been sent in /html/wordpress/wp-content/plugins/jet-search/includes/ajax-handlers.php on line 187
```

**Comment by RoundAboutWEB** [comment]
Hello

**Comment by MjHead** [comment]
@RoundAboutWEB Thanks for reporting, we'll check this

**Comment by MjHead** [comment]
@RoundAboutWEB I checked it on lates JetSearch version. There is no such bug. Please try to update JetSearch and try again. If bug still exists, please go here - https://tppr.me/6Ydgz and make sure Use session option is disabled (even if it disabled, just in case, please try to enable it save options, and than disable again)

**Comment by RoundAboutWEB** [comment]
Thanks, Bug will be fixed with new Version since 16. September

![grafik](https://github.com/Crocoblock/jet-ai-search/assets/26809494/3baaede0-8abd-40bc-8950-e18c36e03701)
